--
-- Migration - Step 1
-- Adding new entity to database schema
--
CREATE TABLE `COUNTRY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `ISOCODE` varchar(3) NOT NULL,
  PRIMARY KEY (`ID`)
) AUTO_INCREMENT=1 ;

CREATE TABLE `COUNTRY_CURRENCY` (
  `COUNTRY_ID` bigint(20) NOT NULL,
  `CURRENCY_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`COUNTRY_ID`,`CURRENCY_ID`)
) ;

CREATE TABLE `CURRENCY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `ISOCODE` varchar(3) NOT NULL,
  PRIMARY KEY (`ID`)
) AUTO_INCREMENT=1 ;

CREATE TABLE `PRICE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AMOUNT` float NOT NULL,
  `CURRENCY_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) AUTO_INCREMENT=1 ;

CREATE TABLE `PRODUCT_PRICE` (
  `PRODUCT_ID` bigint(20) NOT NULL,
  `PRICE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`,`PRICE_ID`)
) ;

-- Adding constraints
ALTER TABLE `COUNTRY_CURRENCY` ADD CONSTRAINT `FK_COUNTRY_CURRENCY_CURRENCY_ID` 
	FOREIGN KEY (`CURRENCY_ID`) REFERENCES `CURRENCY` (`ID`);
ALTER TABLE `COUNTRY_CURRENCY` ADD CONSTRAINT `FK_COUNTRY_CURRENCY_COUNTRY_ID` 
	FOREIGN KEY (`COUNTRY_ID`) REFERENCES `COUNTRY` (`ID`);
ALTER TABLE `PRICE` ADD CONSTRAINT `FK_PRICE_CURRENCY_ID` 
	FOREIGN KEY (`CURRENCY_ID`) REFERENCES `CURRENCY` (`ID`);
ALTER TABLE `PRODUCT_PRICE` ADD CONSTRAINT `FK_PRODUCT_PRICE_PRICE_ID` 
	FOREIGN KEY (`PRICE_ID`) REFERENCES `PRICE` (`ID`);
ALTER TABLE `PRODUCT_PRICE` ADD CONSTRAINT `FK_PRODUCT_PRICE_PRODUCT_ID` 
	FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`);

-- Adding a field to PRODUCT (with null allowed)
ALTER TABLE `PRODUCT` ADD COLUMN `TYPE` varchar(15) NULL;
